### ISSUE TITLE
High concurrency value causes race condition in the commit stage 

### ISSUE THREAD

**Issue by Abdulsametileri** [Trendyol/kafka-konsumer#30] opened 2023-09-04 08:16 UTC
We observed that any concurrency value greater than 1 causes race conditions on the Kafka side. Let's look into more detail.

![image](https://github.com/Trendyol/kafka-konsumer/assets/19360039/76c6bee6-ffbd-4fc3-b1f6-cbeff9d2847e)

Let's assume that the user provides a concurrency value of 4. It means we need to spawn 4 goroutines. As we already know, the go scheduler manages the goroutines so it is not possible to know which goroutine will be executed. Because of it race condition occurs. 

For example, if g1 runs before g2 first we commit `offset 5-10` and after `10-15`. No problem
But if g2 runs before g1, we commit offset `10-15` and after `5-10`. 

Because of it, although we processed and committed offset, the lag still remains :(. 

**Note: If you need to quick fix, you can give a concurrency value of 1.**

We will address this problem asap.

**Comment by Abdulsametileri** [comment] 2023-09-04 08:41
We can use `ReadMessage` instead of Fetch and Commit Messages.

**Comment by oguzhaneren** [comment] 2023-09-04 08:50
storing higher offset in lock-free list can help, instead of committing directly, goroutine can add latest offset to OffsetList and another goroutine can consume from list for commiting.

**Comment by Abdulsametileri** [comment] 2023-09-04 09:02
We thought about this scenario. Let's look;

What if g1 and g3 store their offset in the lock-free list while g2 still executing, The committer goroutine commits the latest `offset 20` after the G2 is finished committer goroutine commits the latest offset `15`. The lag displayed as 5 :/ 

So It's like not a solution to this problem

![image](https://github.com/Trendyol/kafka-konsumer/assets/19360039/4c2496c7-639e-4f9e-a228-cf5a29703ae6)

**Comment by oguzhaneren** [comment] 2023-09-04 10:22
you don't need store offset is lower than already committed. 

in your scenario, if g3 already committed you don't need commit or store offset of g1 and g2

**Comment by Abdulsametileri** [comment] 2023-09-04 11:14
Yes, I got it 😌  we can experiment this but multiple topic case are little bit complex 😕 

I want to ask another question. What do you think about this re-design?

![image](https://github.com/Trendyol/kafka-konsumer/assets/19360039/6d60d259-dde3-466b-aac6-5b0ac18dc35e)

In kafka-go lib there is a method called `ReadMessage` In this method, as soon as the messages received, they are committed

```go
func (r *Reader) ReadMessage(ctx context.Context) (Message, error) {
	m, err := r.FetchMessage(ctx)
	if err != nil {
		return Message{}, err
	}

	if r.useConsumerGroup() {
		if err := r.CommitMessages(ctx, m); err != nil {
			return Message{}, err
		}
	}

	return m, nil
}
```

In `g0` fetch and commit messages and send it to channel, other goroutines listen to that channel and invokes `batchConsumeFn`

In this scenario, we need to guide the user about graceful shutdown because although we are not processing message, we committed

We tried this architecture is very performant! [here](https://medium.com/trendyol-tech/new-winner-of-kafka-consumers-scala-to-go-journey-604c6bdd7041)

**Comment by oguzhaneren** [comment] 2023-09-04 11:28
commitring offset before processing messages can be little problematic because we can loose messages if application shutdown immediately or any unexpected things happen in pod or application.

graceful shutdown is must here also application should reproduce committed but not processed messages to kafka, but what happen if application cannot procude these messages to kafka? I think handling this failure scenario is more complex than managing thread-safe list per topic for managing/tracking committed/uncommitted offsets. 🤔

**Comment by Abdulsametileri** [comment] 2023-09-04 11:31
Thank you for your valuable comments, these concerns are really crucial!

We will experiment and test your recommended implementation ASAP 😅

**Comment by Abdulsametileri** [comment] 2023-09-06 06:46
Based on my experiments, managing a thread-safe list is good but when rebalancing happens we need to delete and create this list so kafka-go does not present this kind of eventing 😕 This is very challenging 🤔 @oguzhaneren 

https://github.com/Trendyol/kafka-konsumer/pull/33/files#diff-3d7d7694e24a977b9c4e30d03880ff4929efaeb873e7850edc4c110388b40da0R116

**Comment by oguzhaneren** [comment] 2023-09-06 08:52
I don't know api of the segmentio but I took a look, there is a variable for assigned topic/partitions

https://github.com/segmentio/kafka-go/blob/main/consumergroup.go#L321

maybe we can ensure committing topic/partition existsince by looking this map in committing goroutine, if is not in the list we can simply ignore the offset because this partition rebalanced to another client. what do you think?

**Closed** 2023-09-06 12:07 UTC
Labels: bug

**Comment by Abdulsametileri** [comment] 2023-09-24 15:06
@mhmtszr
